[package]
name = "exile-controller"
version = "0.4.0"
edition = "2021"
license = "MIT"

[dependencies]
config = {version = "0.15.19"}
serde = {version = "1.0.228", features = ["derive"]}
gilrs = {version ="0.11.0", default-features = false, features = ["serde-serialize", "xinput"]}
rdev = {version = "0.5.3", features = ["serialize"]}
active-win-pos-rs = "0.9.1"
native-dialog = "0.9.4"
mouse_position = "0.1.4"

# egui
egui = "0.33"
egui_extras = {version = "0.33", features = ["all_loaders"]}
eframe = { version = "0.33.0", default-features = false, features = [
    "default_fonts", # Embed the default egui fonts.
    "wgpu",
    # Wayland is disabled until a window can be reliably placed/sized. =(
    # "wayland",
    "x11",
] }
wgpu = {version = "27.0.1", optional = true, default-features = false}
image = { version = "0.25", features = ["png"] }

[features]
default = ["normal-backends"]
normal-backends = ["wgpu/default"]
blackscreen-workaround = ["wgpu/std", "wgpu/parking_lot", "wgpu/gles"]

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[[bin]]
name = "exile-controller"
path = "src/main.rs"
