[package]
name = "exile-controller"
version = "0.3.0"
edition = "2021"
license = "MIT"

[dependencies]
config = "0.15.19"
serde = {version = "1.0.228", features = ["derive"]}
gilrs = {version ="0.11.0", default-features = false, features = ["xinput"]}
rdev = "0.5.3"
active-win-pos-rs = "0.9.1"
native-dialog = "0.9.4"

# egui
egui = "0.29"
egui_overlay = { version = "0.9.0", features = ['three_d']}
egui_extras = {version = "0.29", features = ["all_loaders"]}
image = { version = "0.25", features = ["png"] }
egui_window_glfw_passthrough = "0.9.0"


[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[[bin]]
name = "exile-controller"
path = "src/main.rs"
