[package]
name = "exile-controller"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
config = "0.13.3"
serde = "1.0.151"
gilrs = {version ="0.10.1", default-features = false, features = ["xinput"]}

[[bin]]
name = "exile-controller"
path = "src/main.rs"
