# Enables move-aiming with the right stick
# Bumpers, triggers and cardinal face buttons only only!
aimable_buttons = ["RightTrigger"]

# Sets action distance from character when pushed while moving or move-aiming. 
# Ideal for setting movement skill distances, totem drop distances, etc
# Must be close/mid/far; Aimable buttons without this will snap to "walk" distance.
# When not moving or move-aiming, all skills target current mouse position without snapping.
# May get weird if holding several buttons.
# Bumpers, triggers and cardinal face buttons only!
action_distances = {West = "Far", South = "Mid"}

# You must bind your left-click ability in PoE to movement.
# You must also let the game use default ability mappings for QWERT
# To bind no keypress to a button, set the binding to "Empty"
[button_mapping]
West = {Key = "KeyQ"}
North = {Key = "KeyR"}
South = {Key = "KeyW"}
East = {Key = "KeyE"}
Start = {Key = "KeyI"}
Select = {Key = "Alt"}
DPadDown = {Key = "Num2"}
DPadLeft = {Key = "Num1"}
DPadRight = {Key = "Num3"}
DPadUp = {Key = "Num4"}
LeftThumb = "Empty" #L3
RightThumb = {Key = "Num5"} #R3
LeftTrigger = {Button = "Middle"}
RightTrigger = {Button = "Right"}
LeftTrigger2 = {Key = "Escape"}
RightTrigger2 = {ButtonKeyChord = ["Left", "Alt"]}

[overlay]
screen_height = 1080
screen_width = 1920
show_crosshair = true
show_buttons = true
# Cannot currently have both always_show_overlay and windowed_mode set to true
always_show_overlay = false
windowed_mode = false

[controller]
walk_circle_radius_px = "110"
close_circle_radius_px = "100"
mid_circle_radius_px = "250"
far_circle_radius_px = "400"
character_x_offset_px = "0"
character_y_offset_px = "100"
dead_zone_percentage = "0.17"
free_mouse_sensitivity_px = "10"
controller_type = "Auto" # Must be set to {Forced = "Playstation"}, {Forced = "Xbox"}, "Auto"
